### ISSUE TITLE
Site design and CSS

### ISSUE THREAD

**Issue by Suzii** [tomaskristof/event-planner#1]
1. Propose design for all the pages of the application, ideally by creating wireframes.
2. Create logo.
3. Create CSS files for the web sites.
4. Add styling to all views - .cshtml files.

**Comment by japarmezan** [comment]
1) Wireframes for 3 pages created: 
- Index page
- Page after logging in
- Page for creating new Event

**Comment by japarmezan** [comment]
2) Logo created and overview is in Design folder. Need to create transparent version for Navigation bar.

**Comment by japarmezan** [comment]
3) LESS files put into EventPlanner.Bootstrap and changed to blue theme.

**Comment by japarmezan** [comment]
5) Take a look at compilation of less resources with Gulp 101 and Task Runner.

**Comment by Suzii** [comment]
Done and dusted.
