### ISSUE TITLE
MVC: DatePickers - Create and Edit pages

### ISSUE THREAD

**Issue by Suzii** [tomaskristof/event-planner#11]
1. Find a suitable libary for working with datepickers.
2. Add datepickers to Create and Edit pages.
3. Implement multiple time selections based on dates picked from datepicker.
4. Make sure all selected dates and times will get posted on submit and will be properly bind by controller to Action's model properties.

**Comment by Suzii** [comment]
1. Datepickers are currently implemented using bootstrap-datepicker3 library
2. Datepickers added, logic sits in NewDate.js file, datepickers are dynamically added also to fields that are created on demand.
3. Time Selections are now in place, hidden input field for timeslot id is present for every time selector to enable editing. NewTime.js file is broken due to model changes.
4. Binding works ok.

**Outstanding issues:**
- NewTime.js file requires refactoring - logic was broken when introducing TimesModel which changed id and name attributes of input elements.   DONE
- Add delete button for all but first date input fields.  DONE
- Add delete button for all but first time input fields. DONE
- It would be better to enclose every group of inputs that contain date input into separate _div_ element currently in span)
- When editing event with multiple dates and times, adding new date generated wrong index for new fields.  DONE
- Include bootstarp-datepicker3 less files and generate css dynamically. DONE by Janka
- After delete a time in the middle - change id of the rest of times DONE

**Comment by Akaren13** [comment]
Everything above done.

**Outstanding issues:**
- After editing time nullPointerException is thrown during parse new time.

**Comment by Suzii** [comment]
Fixed by [this commit](https://github.com/tomaskristof/event-planner/commit/24e18fc44d5d39f43eaa536000d5a309d2c2f510).

**Outstanding Issues:**
- Entered date disappears once opening date picker without selecting any date and then closing it.
