### ISSUE TITLE
Service layer

### ISSUE THREAD

**Issue by Suzii** [tomaskristof/event-planner#4]
1. Design service API to best suit needs of the application.
2. Create EventPlanner.Service project.
3. Create interfaces with detailed comments for all the services.
4. Create implementation for all the services, using DAL priject and FourSquare project.

**Comment by tomaskristof** [comment]
1. Designing service API is in progress
2. EventPlanner.Service project created
3. Current interfaces:
   IEventManagementService - CRUD operations, handling logic about events
   IPlaceService - Communication with FourSquare project
   IUserService - Specific operations related to event management for each user (NOT password reset, ...)
   IVotingService - Handling voting logic
   More interfaces can be added...
4. Completed implementation:
   PlaceService

**Comment by tomaskristof** [comment]
Added new interface - IEventDetailsService containing methods to operate with event detail
Completed implementation for every interface
