### ISSUE TITLE
FourSquare library

### ISSUE THREAD

**Issue by Suzii** [tomaskristof/event-planner#5]
1. Explore possibilities of FourSquare API.
2. Create EventPlanner.Foursquare project.
3. Create an inteface that would serve as an easy-to-use library mediating access to FourSquare API.
   a) It has to be able to search for venues by city+query.
   b) Retrieve the Venue based on VenueId.
4. Create an implementation for the interface.

**Comment by tomaskristof** [comment]
1. There are many options what we can do :) More info at https://developer.foursquare.com/docs/
2. EventPlanner.Foursquare project created
3. Interface provides access to two async methods
   a) GetVenueSuggestionsAsync - retrieves response containing list of miniVenue suggestions for required query and location
   b) GetVenueAsync - retrieves response containing all informations about venue based on given ID
4. Implementation of interface created. FS module proccess more venue informations than is needed by Web project.
