### ISSUE TITLE
MVC: Voting page

### ISSUE THREAD

**Issue by Suzii** [tomaskristof/event-planner#7]
1. In EventPlanner.Web create Voting page.
2. Page of an specific event will be accessible by a unique URL distributed by creator of an event.
3. Page will enable voting for both dates and places separately.
4. If user is eligeable for editing of an event, there will be a visible link redirecting to Edit Event page.

**Comment by Suzii** [comment]
Voting page created. Currently displays faked event recieved from stubbed service EventManagmentService. 

Page displays overal votes for places and dates, plus enebles logged in user to vote for places and dates. If user already voted for given event, the form will be prefilled with previously selected options and user is able to edit them. VotingService is not implemented yet, therefore submitting the form ends with an exception.

There is still a lot of stylying to be done as well as Google Maps module that will be added to the page. It will display places asocciated with the event.

**Comment by Suzii** [comment]
Voting modules for both Places and Dates are written in ReactJS. Every vote is posted via AJAX to VoteController and directly stored to database, with current state of the voting app updatin automatically.
Google maps module shows all places associated with event. Goal is to provide list of places next to map with a popup displayed on the map once clicking on place link.

**Comment by japarmezan** [comment]
5) There was implemented map module, which includes:
- Markers of all places included in voting.
- Info window shows on click on the marker.
- Side panel with list of places. Hover on item causes highlight of marker on the map.
- Hover on the marker causes highlight of item in list.

Everything is also superfancy.

**Comment by japarmezan** [comment]
- Added support for touch screens for map. If place item is clicked, marker keeps highlighted and map centers to this point.
