### ISSUE TITLE
MVC: Profile page

### ISSUE THREAD

**Issue by Suzii** [tomaskristof/event-planner#8]
1. In EventPlanner.Web create page that would serve as a User Profile page.
2. Page will display basic info about the user, with option for changing the password.
3. Page will display list all the events created by the user.
4. For every Event displayed on the page, it will contain a link for Edit and Vote page of the Event.

**Comment by japarmezan** [comment]
My suggestion is putting info about user's events separately under the Home tab and rename it to sth like "My events".
User profile is already partially implemented by Identity, under the login tab on the right side.
